from typing import List, Optional, Dict
import torch

TensorDict = Dict[str, torch.Tensor]


class BatchRunner:
    def __init__(self, py_model: torch.jit.ScriptModule, device: str, max_batch_size: Optional[int],
                 methods: Optional[List[str]]): ...

    def add_method(self, method: str, batch_size: int): ...

    def start(self): ...

    def stop(self): ...

    def update_model(self, py_model: torch.jit.ScriptModule): ...

    def set_log_freq(self, log_freq: int): ...

    def block_call(self, method: str, t: TensorDict): ...


class ThreadLoop: ...


class Context:
    def __init__(self): ...

    def push_thread_loop(self, env: ThreadLoop) -> int: ...

    def start(self): ...

    def pause(self): ...

    def resume(self): ...

    def join(self): ...

    def terminated(self): ...


class ModelLocker:
    def __init__(self, py_models: List[torch.jit.ScriptModule], device: str): ...

    def update_model(self, py_model: torch.jit.ScriptModule): ...


class BatchProcessor:
    def __init__(self, model_locker: ModelLocker, func_name: str, batch_size: int, device: str): ...


class Models:
    def __init__(self): ...

    def add(self, call_name: str, processor: BatchProcessor): ...
